### ISSUE TITLE
在BungeeCord端出现了一个异常

### ISSUE THREAD

**Issue by flowerinsnowdh** [CarmJos/MineConfiguration#13]
### **问题简述**

我在`onEnable`方法中初始化了一个配置文件，出现了一个异常

### **问题来源**
调用方法：
```java
ConfigInitializer<BungeeConfigProvider> config = new ConfigInitializer<>(
        new BungeeConfigProvider(new File(getDataFolder(), "config.yml"), ConfigurationProvider.getProvider(YamlConfiguration.class))
);
config.initialize(BlessingConfig.class, true, true);
```

`BlessingConfig.java`：
```java
public class BlessingConfig extends ConfigurationRoot {
    @ConfigPath("server_name")
    @HeaderComment({"全局前缀", "将用于数据存储处"})
    public static final ConfigValue<String> GLOBAL_PREFIX = ConfiguredValue.of(String.class, "UNSET");

    @ConfigPath("sql")
    @HeaderComment("MySQL配置")
    public static class SQL {
        @ConfigPath("host")
        @HeaderComment("MySQL主机")
        public static final ConfigValue<String> HOST = ConfiguredValue.of(String.class, "127.0.0.1");

        @ConfigPath("port")
        @HeaderComment("MySQL端口")
        public static final ConfigValue<Integer> PORT = ConfiguredValue.of(Integer.class, 3306);

        @ConfigPath("schema")
        @HeaderComment("MySQL库")
        public static final ConfigValue<String> SCHEMA = ConfiguredValue.of(String.class, "minecraft");

        @ConfigPath("username")
        @HeaderComment("MySQL用户名")
        public static final ConfigValue<String> USERNAME = ConfiguredValue.of(String.class, "root");

        @ConfigPath("password")
        @HeaderComment("MySQL密码")
        public static final ConfigValue<String> PASSWORD = ConfiguredValue.of(String.class, "root");

        @ConfigPath("init_size")
        @HeaderComment("数据库连接池初始连接数")
        public static final ConfigValue<Integer> INIT_SIZE = ConfiguredValue.of(Integer.class, 8);

        @ConfigPath("max_active")
        @HeaderComment("数据库连接池最大连接数")
        public static final ConfigValue<Integer> MAX_ACTIVE = ConfiguredValue.of(Integer.class, 16);

        @ConfigPath("max_wait")
        @HeaderComment("数据库连接池最大等待时间")
        public static final ConfigValue<Long> MAX_WAIT = ConfiguredValue.of(Long.class, 3000L);
    }
}
```

出现异常：
```log
java.lang.NullPointerException: Cannot invoke "cc.carm.lib.configuration.core.source.ConfigurationWrapper.contains(String)" because the return value of "cc.carm.lib.configuration.core.value.ConfigValue.getConfiguration()" is null
    at cc.carm.lib.configuration.core.value.ConfigValue.setDefault(ConfigValue.java:117)
    at cc.carm.lib.configuration.core.value.ConfigValue.setDefault(ConfigValue.java:107)
    at cc.carm.lib.configuration.core.value.ConfigValue.initialize(ConfigValue.java:44)
    at cc.carm.lib.configuration.core.ConfigInitializer.initializeValue(ConfigInitializer.java:117)
    at cc.carm.lib.configuration.core.ConfigInitializer.initializeField(ConfigInitializer.java:94)
    at cc.carm.lib.configuration.core.ConfigInitializer.initializeClass(ConfigInitializer.java:74)
    at cc.carm.lib.configuration.core.ConfigInitializer.initialize(ConfigInitializer.java:49)
    ............
```

### **操作环境**

- 系统环境: `Ubuntu`
- Java版本: `openjdk version "17.0.4"`
- `/bungee`命令：`This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:2d369e8:1664 by md_5`

使用的依赖：
```xml
<dependency>
    <groupId>cc.carm.lib</groupId>
    <artifactId>easysql-impl</artifactId>
    <version>0.4.6</version>
</dependency>
```

**Comment by CarmJos** [comment]
```java
    @Override
    public void onLoad() {
        ConfigurationProvider<?> provider = MineConfiguration.from(this,"config.yml");
        provider.initialize(PluginConfig.class);
    }
```

**Comment by CarmJos** [comment]
另外，无需每一个字段都单独添加“`@ConfigPath`”。一般来说，会更具类名与变量名自动生成。

如 `BlessingConfig.SQL.USERNAME`，通过 `ConfigurationProvider#initialize(class)`后在配置文件中的字段是“<ROOT>.sql.username”。

**Comment by flowerinsnowdh** [comment]
谢谢，问题已解决
