### ISSUE TITLE
[Bungee] 无法正常加载配置文件

### ISSUE THREAD

**Issue by huanmeng-qwq** [CarmJos/MineConfiguration#47]
### **问题简述**

无法正常加载配置文件

### **问题来源**

最近更新依赖库版本，easyconfiguration从3.2.0到3.8.0，mineconfiguration从2.1.0升级到2.8.7出现了下面的报错，实测Bukkit平台没有问题 ~~(猜想: 感觉在Bungee的那块加一个异常捕获ignored就可以?)~~

 ```[01:10:24 ERROR]: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class net.md_5.bungee.config.Configuration (java.lang.Boolean is in module java.base of loader 'bootstrap'; net.md_5.bungee.config.Configuration is in unnamed module of loader 'app')
[01:10:24 ERROR]:       at net.md_5.bungee.config.Configuration.getSection(Configuration.java:143)
[01:10:24 ERROR]:       at cc.carm.lib.mineconfiguration.bungee.source.BungeeConfigProvider.getKeys(BungeeConfigProvider.java:91)
[01:10:24 ERROR]:       at cc.carm.lib.yamlcommentupdater.CommentedYAMLWriter.writeWithComments(CommentedYAMLWriter.java:50)
[01:10:24 ERROR]:       at cc.carm.lib.yamlcommentupdater.CommentedYAMLWriter.writeWithComments(CommentedYAMLWriter.java:25)
[01:10:24 ERROR]:       at cc.carm.lib.mineconfiguration.bungee.source.BungeeConfigProvider.save(BungeeConfigProvider.java:62)
[01:10:24 ERROR]:       at cc.carm.lib.configuration.core.ConfigInitializer.initialize(ConfigInitializer.java:56)
[01:10:24 ERROR]:       at cc.carm.lib.configuration.core.ConfigInitializer.initialize(ConfigInitializer.java:37)
[01:10:24 ERROR]:       at cc.carm.lib.configuration.core.source.ConfigurationProvider.initialize(ConfigurationProvider.java:117)
[01:10:24 ERROR]:       at cc.carm.lib.configuration.core.source.ConfigurationProvider.initialize(ConfigurationProvider.java:107)
[01:10:24 ERROR]:       at ConfigManager.<init>(ConfigManager.java:27)
```
```java
     public ConfigManager(ConfigurationProvider<?> configurationProvider) {
     #line 27   configurationProvider.initialize(XXXConfig.class);
    }
```

> XXXConfig里面是一堆子类加上ConfiguredValue<Integer>、ConfiguredValue<String>、ConfiguredValue<Boolean>的配置项 没有其他类型的内容

### **问题截图/问题报错**

![image](https://github.com/CarmJos/MineConfiguration/assets/49704373/b83a1274-d534-49d5-95c1-b386570ba1d7)

### **操作环境**

- 系统环境: Debian GNU/Linux 10
- Java版本: Java18

### **其他补充**

- Waterfall 1.19
- MineCondifuration 2.8.7
- EasyConfiguration 3.8.0

**Comment by huanmeng-qwq** [comment]
@CarmJos

**Comment by CarmJos** [comment]
Bungee项目建议直接换用 EasyConfiguration-YAML 。

**Comment by CarmJos** [comment]
然后这个提示应该是缺少java模块，可以百度一下吧模块添加上去即可。

**Comment by huanmeng-qwq** [comment]
> 然后这个提示应该是缺少java模块，可以百度一下吧模块添加上去即可。

这好像是getKeys方法在调用getSection然后通过get(String)获得的object是一个String 但是getSection尝试把他cast为一个Configuration导致的错误

**Comment by CarmJos** [comment]
> > 然后这个提示应该是缺少java模块，可以百度一下吧模块添加上去即可。
> 
> 这好像是getKeys方法在调用getSection然后通过get(String)获得的object是一个String 但是getSection尝试把他cast为一个Configuration导致的错误 ClassCastException

根本原因应该是缺少了一个模块，加一个module就可以了。

**Comment by CarmJos** [comment]
如果实在不行就换用EASY-YAML吧，BC的配置文件一直都很迷。

**Comment by huanmeng-qwq** [comment]
> > > 然后这个提示应该是缺少java模块，可以百度一下吧模块添加上去即可。
> > 
> > 
> > 这好像是getKeys方法在调用getSection然后通过get(String)获得的object是一个String 但是getSection尝试把他cast为一个Configuration导致的错误 ClassCastException
> 
> 根本原因应该是缺少了一个模块，加一个module就可以了。

是bungee服务端目录/modules里面的那个模块吗 我一直没装

**Comment by CarmJos** [comment]
> > > > 然后这个提示应该是缺少java模块，可以百度一下吧模块添加上去即可。
> > > 
> > > 
> > > 这好像是getKeys方法在调用getSection然后通过get(String)获得的object是一个String 但是getSection尝试把他cast为一个Configuration导致的错误 ClassCastException
> > 
> > 
> > 根本原因应该是缺少了一个模块，加一个module就可以了。
> 
> 是bungee服务端目录/modules里面的那个模块吗 我一直没装

不是，是JAVA的模块，高版本java分模块了，有些需要自己加启动参数来启用。

**Comment by huanmeng-qwq** [comment]
具体是哪一个模块，百度搜这个报错没解决方案

**Comment by CarmJos** [comment]
> 具体是哪一个模块，百度搜这个报错没解决方案

我也不清楚呀，建议换YAML。

**Comment by huanmeng-qwq** [comment]
好吧

**Comment by huanmeng-qwq** [comment]
```
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'
        at org.bspfsystems.yamlconfiguration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:160) ~[yamlconfiguration-1.2.1.jar:?]
        at org.bspfsystems.yamlconfiguration.file.FileConfiguration.load(FileConfiguration.java:157) ~[yamlconfiguration-1.2.1.jar:?]
        at org.bspfsystems.yamlconfiguration.file.FileConfiguration.load(FileConfiguration.java:176) ~[yamlconfiguration-1.2.1.jar:?]
        at org.bspfsystems.yamlconfiguration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:451) ~[yamlconfiguration-1.2.1.jar:?]
        at cc.carm.lib.configuration.yaml.YAMLConfigProvider.initializeConfig(YAMLConfigProvider.java:29) ~[easyconfiguration-yaml-3.8.0.jar:?]
        at cc.carm.lib.configuration.EasyConfiguration.from(EasyConfiguration.java:17) ~[easyconfiguration-yaml-3.8.0.jar:?]
        at cc.carm.lib.configuration.EasyConfiguration.from(EasyConfiguration.java:25) ~[easyconfiguration-yaml-3.8.0.jar:?]
```
